### PR TITLE
Added Title & Brand Name

### PR DESCRIPTION
**Pull request by SMak06**
changed Brand Name size as well

General Guidelines:

- Do not use SMS language.
- Ideally, each line should be less than 72 characters
- Title should be ideally less than 50 characters
- Make sure that the title and message are descriptive for your pull request and all your commits.
- Last line of the commit and PR should be: closes <#issue-id>

Pull Request Guidelines:

- About should be ideally one word, example: [Bug], [Enhancement]
- Remove this message before making the PR, it's only here to help the newcomers.

In Doubt? See Example: https://github.com/atb00ker/robotics.github.io/pull/5

### CODE REVIEW

**Comment by atb00ker** [comment]
Buddy it's not an ALiAS Website, we are making it for Amity Embedded and Robotics Club (ERC).

**Comment by SMak06** [comment]
Ahhhh okay

Brief me a bit more, I can help develop it.

**Comment by atb00ker** [comment]
**About**
We often dull ourselves into complacency with the way things are.
While growing up there's an idea that is induced into our brains that the world is something that happens right outside your peepers and you just try to find your place and fit in while you see some other 'bright' people running it. 
When you start interacting with some of these people you learn that they're not very different from you. They might have a little more judgement in some areas but they're basically the same.
There's something beyond what is going on in this life, something beyond a house, a car and a set monotous lifestyle that a human being is dulled into. There is another side to this coin and you'll see that the moment you realise that if you push something here, another thing pops out on the other side. So be a round peg in a square hole. That way you've got a lot of room to fill in with something that is different. 
When you work on something, don't think about the non ideal consequences, let the idealism drive you. The non ideal consequences only play one role and that is to balance each other out. There's a reason why seeking idealism is the goal. 
It doesn't matter if you're taking a step a day, you'll still be farther from if you thought for days and took the same step.
As Bob Dylan rightly said
"The chance wont come again,
and don't speak too soon
For the wheels still in spin' 
and there's no tellin' who that its namin'
For the loser now will be later to win
For the times they are a-changin"

**Comment by atb00ker** [comment]
Thanks for the work, but it is made obsolete by #13 , hence i am closing it!

**Pull request closed without merging**
